language: ruby
sudo: false

rvm:
  - 2.3.3
  - 2.4.1

before_install: gem update bundler --no-document

gemfile:
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x

matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.4.2.x
